-- Criação do banco de dados
CREATE DATABASE IF NOT EXISTS pet_shop;
USE pet_shop;

-- Criação da tabela de interessados
CREATE TABLE IF NOT EXISTS interessados (
  id INT AUTO_INCREMENT PRIMARY KEY,
  cpf VARCHAR(14) NOT NULL UNIQUE,
  nome VARCHAR(100) NOT NULL,
  telefone VARCHAR(15) NOT NULL,
  email VARCHAR(100) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Criação da tabela de filhotes
CREATE TABLE IF NOT EXISTS filhotes (
  id INT AUTO_INCREMENT PRIMARY KEY,
  especie VARCHAR(50) NOT NULL,
  raca VARCHAR(50) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
); 